### ISSUE TITLE
Sort databases, containers alphabetically in tree view

### ISSUE THREAD

**Issue by Arithmomaniac** [thomaslevesque/CosmosDBStudio#50]
I don't know why they don't come that way from the API, but it makes it hard to pick out a container when you have more than a handful.

**Comment by thomaslevesque** [comment]
Oh! I never noticed they weren't returned in order. I guess I never had more than a handful of containers in my test databases.
Good idea, thanks for the suggestion!

**Comment by Arithmomaniac** [comment]
I have 50 in one database to get around the throughput limits while in

**Comment by ricardopinedathen** [comment]
I think this can be closed now 👍

**Comment by thomaslevesque** [comment]
> I think this can be closed now or is it closed when the release is available?

The issue will be closed when I merge your PR, but you closed your PR, so... :wink:
