### ISSUE TITLE
Error while launching CosmosDb Studio

### ISSUE THREAD

**Issue by magob-sagefr** [thomaslevesque/CosmosDBStudio#51]
Hi,
I tested your project and greatly appreciated it : many thanks !

A colleague of mine wanted to used it, but faced an error message while launching CosmosDb Studio be it installed through the App store or by sideloading.
His Windows 10 version is 19041, so should be okay with your requirements.

Is there any kind of redistributable that we should be aware of to make it run properly ?

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/58553416/110347909-60c1d280-8031-11eb-9eae-21fb36d55d24.png)

**Comment by thomaslevesque** [comment]
Hi @magob-sagefr,

Wow, I've never seen an exception like this... Looks like an error in native code.
Does your colleague have SQL Server installed? It could be related to [this](https://support.microsoft.com/fr-fr/topic/kb4073393-r%C3%A9soudre-l-erreur-la-zone-de-donn%C3%A9es-transmise-%C3%A0-un-appel-syst%C3%A8me-est-trop-petite-lorsque-vous-d%C3%A9marrez-une-application-desktop-bridge-sur-un-serveur-sql-server-5ae0994d-023a-d32b-3aad-526500b53993)

**Comment by magob-sagefr** [comment]
Hi @thomaslevesque ,
You may have pointed out the problem : the main difference between our environments is SQL Server.
I will let you know when the issue is solved.
Thanks for your quick response

**Comment by magob-sagefr** [comment]
In the end my colleague temporarly stopped SQL Server services and the CosmosDb Studio worked fine !
Thanks for your help
